### ISSUE TITLE
$this->session(['foo' => 'bar']); doesn't populate session

### ISSUE THREAD

**Issue by stubar** [stechstudio/codeception-laravel-unittest#3]
Hi I'm using Laravel4 and trying to populate the session with

$this->session(['foo' => 'bar']);

yet when I call my controller the session is empty.

Any ideas?

**Comment by jszobody** [comment]
I created this for doing unit tests in Laravel 5, I have no idea if this works at all in Laravel 4. Sorry.

**Comment by stubar** [comment]
OK thanks for getting back to me.
