### ISSUE TITLE
Needs updating for Laravel 5.1

### ISSUE THREAD

**Issue by livingos** [stechstudio/codeception-laravel-unittest#6]
Doesn't work in 5.1. 

You need to add the new CrawlerTrait into your CodeceptionLaravelUnitTest. This seemed to get mine working again. Not sure if there are any other issues.

**Comment by livingos** [comment]
Oh and the new  line from 5.1's TesCase:

protected $baseUrl = 'http://localhost';

**Comment by jszobody** [comment]
Merged PR, thanks!
